databases:
  - name: wewrite-db
    plan: free
    region: singapore

services:
  - type: web
    name: wewrite
    env: node
    region: singapore
    plan: free
    buildCommand: yarn --frozen-lockfile --prod=false && blitz build && blitz prisma migrate deploy
    startCommand: blitz start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: wewrite-db
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true
